### ISSUE TITLE
getMatch returns Invalid URL error when checking a match that is either live or upcoming

### ISSUE THREAD

**Issue by rorybush** [gigobyte/HLTV#675] opened 2023-05-15 16:59 UTC
When I try and get the matchpage results for a match that is live or upcoming, I get the below error. Any ideas?

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at /Users/rorybush/Desktop/csgo/node_modules/hltv/lib/endpoints/getMatch.js:194:27
    at Array.map (<anonymous>)
    at getOdds (/Users/rorybush/Desktop/csgo/node_modules/hltv/lib/endpoints/getMatch.js:190:10)
    at /Users/rorybush/Desktop/csgo/node_modules/hltv/lib/endpoints/getMatch.js:75:32
    at step (/Users/rorybush/Desktop/csgo/node_modules/hltv/lib/endpoints/getMatch.js:33:23)
    at Object.next (/Users/rorybush/Desktop/csgo/node_modules/hltv/lib/endpoints/getMatch.js:14:53)
    at fulfilled (/Users/rorybush/Desktop/csgo/node_modules/hltv/lib/endpoints/getMatch.js:5:58) {
  input: '/EksbCB4oDSANS1NLWFtRW0tFSxsIHigNOQUICgwEDAcdIA1LU0s-BhsFDSQIHQoBKwwdHQAHDiUAGh1LRUsbCB4qBhwHHRsQIBoGS1NLLitLRUsbCB4oDT0IDhpLUxJLBAgdCgFLU0tbWl9aUVFQSxRFSxsIHioFAAoCIA0MBx0ADwAMG0tTSxI1Sx0QGQw1S1M1SwYbDkcBBR0fRwgNGkcIGQBHDQgdCEcKBgcPAA4cGwgdAAYHRyYNDRoqBgQZCBsAGgYHJQAaHQAHDigNKgYHDwAOHBsIHQAGB0cmDQ0aKgYEGQgbABoGByUAGh0ABw4lAAcCIA0MBx0ADwAMG0clBg4GJQAHAjVLRTVLBAgdCgEgDTVLU1taX1pRUVAUSxQ=',
  code: 'ERR_INVALID_URL'
}

Node.js v18.10.0

```

**Comment by themod161** [comment] 2023-05-17 15:03
> 
change `providerUrl` in `node_modules/hltv/lib/endpoints/getMatch.js` to
`var providerUrl = new URL('https://www.hltv.org'+oddElement.find('td').first().find('a').attr('href'));`

**Comment by gigobyte** [comment] 2023-06-08 19:07
Fixed in 3.4.6

**Closed by gigobyte** 2023-06-08 19:07 UTC

**Comment by devicarus** [comment] 2023-09-13 18:47
I have the same issue on `3.4.6`
```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at /Users/invoked/Code/hltv-ical/node_modules/.pnpm/hltv@3.4.6/node_modules/hltv/lib/endpoints/getMatch.js:194:27
    at Array.map (<anonymous>)
    at getOdds (/Users/invoked/Code/hltv-ical/node_modules/.pnpm/hltv@3.4.6/node_modules/hltv/lib/endpoints/getMatch.js:190:10)
    at /Users/invoked/Code/hltv-ical/node_modules/.pnpm/hltv@3.4.6/node_modules/hltv/lib/endpoints/getMatch.js:75:32
    at step (/Users/invoked/Code/hltv-ical/node_modules/.pnpm/hltv@3.4.6/node_modules/hltv/lib/endpoints/getMatch.js:33:23)
    at Object.next (/Users/invoked/Code/hltv-ical/node_modules/.pnpm/hltv@3.4.6/node_modules/hltv/lib/endpoints/getMatch.js:14:53)
    at fulfilled (/Users/invoked/Code/hltv-ical/node_modules/.pnpm/hltv@3.4.6/node_modules/hltv/lib/endpoints/getMatch.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  input: '/EksbCB4oDSANS1NLWFteW0tFSxsIHigNOQUICgwEDAcdIA1LU0s-BhsFDSQIHQoBKwwdHQAHDiUAGh1LRUsbCB4qBhwHHRsQIBoGS1NLKjNLRUsbCB4oDT0IDhpLUxJLGQgODEtTSzwHGhkMCgAPAAwNS0VLBAgdCgFLU0tbWl9fWFhcSxRFSxsIHioFAAoCIA0MBx0ADwAMG0tTSxI1Sx0QGQw1S1M1SwYbDkcBBR0fRwgNGkcIGQBHDQgdCEcKBgcPAA4cGwgdAAYHRyYNDRoqBgQZCBsAGgYHJQAaHQAHDigNKgYHDwAOHBsIHQAGB0cmDQ0aKgYEGQgbABoGByUAGh0ABw4lAAcCIA0MBx0ADwAMG0clBg4GJQAHAjVLRTVLBAgdCgEgDTVLU1taX19YWFwUSxQ=',
  code: 'ERR_INVALID_URL'
}

Node.js v18.17.1
```

**Comment by gigobyte** [comment] 2023-09-20 19:25
@devicarus I couldn't reproduce it with currently live or upcoming matches, next time you encounter this issue please post a match ID as well.
