### ISSUE TITLE
Hosting Project -  Methods return empty data

### ISSUE THREAD

**Issue by AlexHill5** [gigobyte/HLTV#23] opened 2017-09-20 21:11 UTC
I made a quick project for school using this awesome package... it was working fine on my local machine... my GetMatches() and GetResults() were returning me the correct data and everything was fine... The only weird(ish) thing I did was call these methods from my NodeJS server and then from there send it to my front end. My front end was getting the data perfectly etc.... I set up a droplet on Digital ocean, pushed my project and got it up and running. Now whenever I try to get the data my Getmatches() and GetResults() return an empty array []. Any idea what this could be?

**Comment by gigobyte** [comment] 2017-09-20 21:19
I'm glad you're happy with the package, I would appreciate any kind of support, even starring :)

Unfortunately, I don't have any experience with Digital Ocean, I can only suggest you to log everything that happens on the server so that you can pinpoint the problem.

**Comment by AlexHill5** [comment] 2017-09-20 21:37
Hey thanks for the quick response, my logs after the methods are invoked are return empty objects/arrays... I'm wondering if the digital ocean server may be doing some weird things. I will continue messing around with it and look into other hosting services. Thank you again!

**Comment by gigobyte** [comment] 2017-09-20 21:46
No problem, man. I'll be closing this as the issue is probably not related to this package.

**Closed by gigobyte** 2017-09-20 21:46 UTC
