### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#18] opened 2017-08-27 21:11 UTC
Sometimes when parsing I get an error that can happen 1000 times (in this case 1373 times): `(node:22516) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1373): TypeError: Cannot read property 'split' of undefined`

**Comment by grandprixgp** [comment] 2017-08-30 03:47
You are not passing the correct variable most likely..

`HLTV.getMatch({id: 1).then(data => {
            console.log(JSON.stringify(data));
        });` = valid
`HLTV.getMatch({1}).then(data => {
            console.log(JSON.stringify(data));
        });` = invalid
`HLTV.getMatch(id: 1).then(data => {
            console.log(JSON.stringify(data));
        });` = invalid

And make sure that you're not somehow passing in a non numeric argument

**Comment by 0ArturkA** [comment] 2017-08-30 07:09
It seems that everything is correct, and I pass a numerical argument:
`HLTV.getMatch({ id: db_match.id }).then(match => { console.log(JSON.stringify(match )); });`

**Comment by grandprixgp** [comment] 2017-08-30 07:39
Any chance you can post a bigger snippet (including db_match.id origin perhaps)?

**Comment by gigobyte** [comment] 2017-08-30 07:45
You can see the full error if you handle the promise rejection
`HLTV.getMatch({ id: db_match.id }).catch(err => console.log(err))`

**Comment by 0ArturkA** [comment] 2017-09-01 15:54
Now get error - `TypeError: Cannot read property 'trim' of undefined`

**Comment by 0ArturkA** [comment] 2017-09-01 16:01
Cant get `additionalInfo` this match - `https://www.hltv.org/matches/2314189/tricked-vs-extatus-mother-russia-1xbet`. Get error - `TypeError: Cannot read property 'trim' of undefined`;

**Comment by gigobyte** [comment] 2017-09-01 16:28
Thanks for the quick feedback. I fixed the issue.

**Comment by 0ArturkA** [comment] 2017-09-05 19:39
![screenshot_1](https://user-images.githubusercontent.com/14136326/30080066-ff611ed4-928a-11e7-9546-699d82f08cac.png)

**Comment by gigobyte** [comment] 2017-09-07 17:17
Closing this issue since there is no way to reproduce it with so little info.

**Closed by gigobyte** 2017-09-07 17:17 UTC
Labels: bug
