### ISSUE TITLE
Team data not parsing

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#10] opened 2017-08-13 21:26 UTC
Sometimes the name or id of one of the teams is not parsed.
`{
"id":2313372,
"team1":{
"name":"Majestic Lions",
"id":6576
},
"team2":{
"name":"",
"id":5412
},
"event":{
"name":"PG WAY Trnava 2017",
"id":null
},
"format":"Best of 3",
"maps":[
"ovp",
"inf",
"mrg"
],
"stars":0,
"live":true
}`

**Comment by 0ArturkA** [comment] 2017-08-14 07:17
You can fix this? Because of this, the module does not work.

**Comment by gigobyte** [comment] 2017-08-14 07:19
Which methods does this bug affect?

**Comment by 0ArturkA** [comment] 2017-08-14 07:27
I meant that this function is very important where I use it and without it nothing works.

**Comment by gigobyte** [comment] 2017-08-14 07:30
You never mentioned which function. From the looks of it, it's the getMatches function, is that correct?

**Comment by 0ArturkA** [comment] 2017-08-14 07:47
Yes, getMatches function.

**Comment by 0ArturkA** [comment] 2017-08-14 13:08
Can you fix?

**Comment by gigobyte** [comment] 2017-08-14 16:45
Issue should be fixed in v2.1.1

**Comment by 0ArturkA** [comment] 2017-08-14 17:58
First live match: `{
"id":2313358,
"team1":{
"name":"Goliath",
"id":8193
},
"team2":{
"name":"",
"id":5153
},
"event":{
"name":"ESEA Open Season 25 South Africa",
"id":3043
},
"format":"Best of 3",
"maps":[
"ovp",
"cch",
"nuke"
],
"stars":0,
"live":true
}`

**Comment by gigobyte** [comment] 2017-08-14 18:06
I can't reproduce it, this bug is fixed in the latest version, have you updated?

`{ id: 2313358,
    team1: { name: 'Goliath', id: 8193 },
    team2: { name: 'eNergy', id: 5153 },
    event: { name: 'ESEA Open Season 25 South Africa', id: 3043 },
    format: 'Best of 3',
    maps: [ 'ovp', 'cch', 'nuke' ],
    stars: 0,
    live: true }`

**Comment by 0ArturkA** [comment] 2017-08-14 18:11
Yes, i update.

**Closed** 2017-08-14 19:16 UTC
Labels: bug
